version: '3'

services:
  nginx:
    image: nginx:1.15.6
    ports:
      - 8888:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./server:/var/www/html
    depends_on: # 追加
      - php
  php:
    container_name: daru_php
    build: ./docker/php
    volumes:
      - ./server:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: daru_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
  
  vue:
    container_name: vue
    build: ./docker/vue
    ports:
      - 8080:8080
    volumes:
      - ./vue:/app
    tty: true